[build]
  base = "agriRental_frontend2-main"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200